/* package codechef; // don't place package name! */

import java.util.*;
import java.lang.*;
import java.io.*;

/* Name of the class has to be "Main" only if the class is public. */
public class Codeforces_1668C_Make_it_Increasing 
{
	public static void main (String[] args) throws java.lang.Exception
	{
	    Scanner sc=new Scanner(System.in);
	    int t=sc.nextInt();
	    int[] arr=new int[t];
	    long previous=0l,current=0l;
	    for(int i=0;i<t;i++){
	        arr[i]=sc.nextInt();
	       
	    }
	    long moves=0L;
	    long min_move=Long.MAX_VALUE;
	    for(int i=1;i<t;i++){
	       previous=0; //setting the origin 0
	       //the loop is a mirror analogy of the logic the lower value is at higher location in array and the higher values are ascending as we move towards lower array indexes
	        for(int j=i-1;j>=0;j--){ 
	            previous+=arr[j]; //adding the current value to previous one in array b gives us a non decreasing value
	            moves+=previous/arr[j]; //finding the moves needed to get current number and adding them
	            previous-=previous%arr[j]; //setting previous to the number generated by performing recent moves
	          
	        }
	       previous=0; //again repeat the process for the ascending values of index from lower to higher
	        for(int k=i+1;k<t;k++){
	            previous+=arr[k];
	            moves+=previous/arr[k];
	            previous-=previous%arr[k];
	        }
	        if(min_move>moves){
	            min_move=moves;
	        }
	        moves=0;
	        
	    }
	    System.out.println(min_move);	// your code goes here
	}
}
